
package Myfiles;

import java.awt.*;
import java.sql.*;
import java.util.Arrays;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Admin extends javax.swing.JFrame {

    Connection conn = null;
    ResultSet rst = null;
    PreparedStatement pst = null;
    String Identity = login.useridentity.getText();
    String na = login.userName.getText();
    String N =login.Designation.getSelectedItem().toString();
    public Admin() {
        initComponents();
        conn = javaconnect.connectdb();
        CurrentDate();
        adduser.setFocusPainted(true);
        Toolkit toolKit = Toolkit.getDefaultToolkit();
        this.setResizable(false);
        Dimension size = toolKit.getScreenSize();
        this.setLocation(size.width/2-this.getWidth()/2,size.height/2-this.getHeight()/2);
        this.setDefaultCloseOperation(Admin.DISPOSE_ON_CLOSE);
        NAME.setText(N+"!");
        exid.setVisible(false);
        exname.setVisible(false);
        exans.setVisible(false);
    }
    public void CurrentDate(){
        Thread clock = new Thread(){     
            @Override
            public void run(){
                for(;;){
                    Calendar cal = new GregorianCalendar();
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int Month = cal.get(Calendar.MONTH)+1;
                    int Year = cal.get(Calendar.YEAR);
                    Date1.setText("Date: "+day+"/"+Month+"/"+Year);
                    int hours = cal.get(Calendar.HOUR)+12;
                    int Minutes = cal.get(Calendar.MINUTE);
                    int Secs = cal.get(Calendar.SECOND);
                    Time1.setText("Time: "+hours+":"+Minutes+":"+Secs+"hrs");
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        clock.start();
    }
    
    public void Cllear(){
        id.setText("");
        name1.setText("");
        address1.setText("");
        email.setText("");
        contact.setText("");
        Answer.setText("");
        passwrd1.setText("");
        passwrd2.setText("");
    }
    private void Update_table(){
        try {
            String sql = "select * from Users"; 
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            }   
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
        try{
            rst.close();
            pst.close();}
            catch(Exception e){}
	}
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Student = new javax.swing.JButton();
        Accounts = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        Answer = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        design = new javax.swing.JComboBox<>();
        VIEW = new javax.swing.JButton();
        SAVE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        UPDATE1 = new javax.swing.JButton();
        passwrd1 = new javax.swing.JPasswordField();
        passwrd2 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox<>();
        address1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        exname = new javax.swing.JLabel();
        exid = new javax.swing.JLabel();
        exans = new javax.swing.JLabel();
        grantAcess = new javax.swing.JButton();
        removeAcess = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        try {
            NAME =(javax.swing.JLabel)java.beans.Beans.instantiate(getClass().getClassLoader(), "Myfiles.Admin_NAME");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jPanel2 = new javax.swing.JPanel();
        SEARCH2 = new javax.swing.JTextField();
        SEARCH = new javax.swing.JButton();
        search1 = new javax.swing.JLabel();
        Time1 = new javax.swing.JLabel();
        adduser = new javax.swing.JButton();
        lablename = new javax.swing.JLabel();
        Date1 = new javax.swing.JLabel();
        Session = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO THE ADMINISTRATION PORTAL OF HAMAD INTERNATIONAL SCHOOL");

        Student.setText("REGISTER STUDENT");
        Student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentActionPerformed(evt);
            }
        });

        Accounts.setText("ACCOUNTS");
        Accounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountsActionPerformed(evt);
            }
        });

        Library.setText("LIBRARY");
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Myfiles/Resources/yellow-light-and-red-student-badge.png"))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ADD/MODIFY USER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        jLabel2.setText("NAME:");

        jLabel4.setText("DESIGNATION:");

        jLabel5.setText("ID");

        jLabel7.setText("CONTACT:");

        jLabel8.setText("CONFIRM PASSWORD:");

        jLabel9.setText("EMAIL:");

        jLabel10.setText("PASSWORD:");

        jLabel11.setText("ADDRESS:");

        name1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        Answer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        id.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        contact.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        email.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        design.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrator", "Class Teacher", "Accountant", "DOS", "Principle", "HM", "Director", " " }));

        VIEW.setText("VIEW USER DETAILS");
        VIEW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWActionPerformed(evt);
            }
        });

        SAVE.setText("SAVE");
        SAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEActionPerformed(evt);
            }
        });

        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });

        UPDATE1.setText("UPDATE");
        UPDATE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATE1ActionPerformed(evt);
            }
        });

        passwrd1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        passwrd2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jComboBox1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is Your Mother's LastName?", "What is Your First School Teacher's Name?", "IWhat is Your Best Friends Name?", "What is Your Favourite Color?", "What is the Name of Your First Love?" }));

        address1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel12.setText("Choose Your Security Question and Answer.");

        exname.setBackground(new java.awt.Color(255, 0, 0));
        exname.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        exname.setForeground(new java.awt.Color(255, 0, 0));
        exname.setText("Name Field is Required");

        exid.setBackground(new java.awt.Color(255, 0, 0));
        exid.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        exid.setForeground(new java.awt.Color(255, 0, 0));
        exid.setText("ID Field is Required");

        exans.setBackground(new java.awt.Color(255, 0, 0));
        exans.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        exans.setForeground(new java.awt.Color(255, 0, 0));
        exans.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        exans.setText("Answer  is Required");

        grantAcess.setBackground(new java.awt.Color(0, 102, 0));
        grantAcess.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        grantAcess.setText("GRANT ACCESS");
        grantAcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grantAcessActionPerformed(evt);
            }
        });

        removeAcess.setBackground(new java.awt.Color(204, 0, 51));
        removeAcess.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        removeAcess.setText("REMOVE ACCESS");
        removeAcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Answer))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contact)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exid, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(exname, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwrd1)
                                    .addComponent(passwrd2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(exans, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(UPDATE1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(VIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(grantAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exid, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(exname, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(design, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwrd1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passwrd2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Answer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exans, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SAVE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UPDATE1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DELETE, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VIEW, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grantAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeAcess, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LOGOUT.setText("LOG OUT");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEARCH FOR USER DETAILS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        SEARCH2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        SEARCH.setText("SEARCH");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });

        search1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        search1.setText("Enter User ID or FirstName.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SEARCH2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SEARCH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(search1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SEARCH2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEARCH, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Time1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Time1.setForeground(new java.awt.Color(0, 0, 255));
        Time1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        adduser.setText("ADD USER");
        adduser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adduserActionPerformed(evt);
            }
        });

        lablename.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lablename.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lablename.setText("Logged in As:");

        Date1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Date1.setForeground(new java.awt.Color(51, 51, 255));
        Date1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        Session.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(adduser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Student)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Session, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Date1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lablename, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Library)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(LOGOUT))
                                    .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Time1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Session, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                            .addComponent(lablename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Student, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Accounts, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Library, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adduser, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed
        login l = new login();
        l.setVisible(true);
        dispose();
    }//GEN-LAST:event_LOGOUTActionPerformed

    private void SAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEActionPerformed
        // TODO add your handling code here:
        try{
            String a = name1.getText();
            String sql= "Insert into Users (UserId,Name,Address,Email,Contact,Designation,Password,Answer) values(?,?,?,?,?,?,?,?)";
            pst= conn.prepareStatement(sql);
            pst.setString(1,id.getText());
            pst.setString(2,name1.getText());
            pst.setString(3,address1.getText());
            pst.setString(4,email.getText());
            pst.setString(5,contact.getText());
            pst.setString(6,design.getSelectedItem().toString());
            pst.setString(8,Answer.getText());
      
            String pss1 = Arrays.toString(passwrd1.getPassword());
            if(pss1.equals(Arrays.toString(passwrd2.getPassword()))){
                if(!Answer.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, a+", has been added Successfully");
                    pst.setNString(7,Arrays.toString(passwrd1.getPassword()));
                    pst.execute();
                    Cllear();
                }
                else if(Answer.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null, "You Must Choose a Security Question and Answer!");
                    exans.setVisible(true);
                }
            }
            else{
                    JOptionPane.showMessageDialog(null,"PASSWORDS DO NOT MATCH");
                    passwrd1.setBackground(Color.RED);
                    passwrd1.setText("");
                    passwrd2.setBackground(Color.RED);
                    passwrd2.setText("");
                    exans.setVisible(false);
                }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table();          
    }//GEN-LAST:event_SAVEActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        try {
            if(SEARCH2.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please Enter User ID or FirstName as Required");
            }
            else{
                String sql = "select * from Users where Name='"+SEARCH2.getText()+"' "; 
                pst = conn.prepareStatement(sql);
                rst = pst.executeQuery();
                Search2 s1 = new Search2();
                s1.setVisible(true);
                SEARCH2.setText("");
            }  
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rst.close();
                pst.close();}
            catch(Exception e){}
	}
    }//GEN-LAST:event_SEARCHActionPerformed

    private void UPDATE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATE1ActionPerformed
        // TODO add your handling code here:
        try{
            int value1 = Integer.parseInt(id.getText());
            String value2 = name1.getText();
            String value3 = address1.getText();
            String value4 = email.getText();
            String value5 = contact.getText();
            String value6 = design.getSelectedItem().toString();
            String value7 = Arrays.toString(passwrd1.getPassword());
            String value8 = Answer.getText();
            String sql= "update Users set UserId = '"+value1+"', Name ='"+value2+"', Address='"+value3+"', Email='"+value4+"', Contact='"+value5+"', Designation='"+value6+"', Password='"+value7+"', Answer='"+value8+"' where ID='"+value1+"' ";          
            pst= conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Update");
            Cllear();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table();
    }//GEN-LAST:event_UPDATE1ActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
        // TODO add your handling code here:
        try{
            String n = name1.getText();
            String a = id.getText();
            if((a.equals("")) && (n.equals(""))){
                exid.setVisible(true);
                exname.setVisible(true);
                
            }
            else if(a.equals(a) && (n.equals(""))){
                exname.setVisible(true);
                exid.setVisible(false);
            }
            else if( n.equals(n) && (a.equals(""))){
                exid.setVisible(true);
                exname.setVisible(false);
            }
            else{
                int answr = JOptionPane.showConfirmDialog(rootPane, "Are You Sure You Want to Delete "+n+"?");
                if(answr == JOptionPane.YES_OPTION){
                    String sql= "Delete from Users where UserId=? and Name=?";
                    pst= conn.prepareStatement(sql);
                    pst.setInt(1, Integer.parseInt(id.getText()));
                    pst.setString(2, n);
                    pst.execute();
                    JOptionPane.showMessageDialog(null,n+" is Successfully Deleted!");
                    id.setText("");
                    name1.setText("");
                    exname.setVisible(false);
                    exid.setVisible(false); 
                }
                if (answr == JOptionPane.NO_OPTION){
                    id.setText("");
                    name1.setText("");
                    exname.setVisible(false);
                    exid.setVisible(false);
                }
                else{
                    exname.setVisible(false);
                    exid.setVisible(false);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        Update_table(); 
    }//GEN-LAST:event_DELETEActionPerformed

    private void VIEWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select * from Users"; 
            pst = conn.prepareStatement(sql);
            rst = pst.executeQuery();
            Search1 ss = new Search1();
            ss.setVisible(true);
    
            }   
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        finally{
            try{
                rst.close();
                pst.close();}
            catch(Exception e){}
	}
    }//GEN-LAST:event_VIEWActionPerformed

    private void StudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentActionPerformed
        // TODO add your handling code here:
      
        String checking = "select * from Access where UserId=? and AccessPage=?";
        String Pagename ="AddStudent";
        
        if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N)) || ("Accountant".equals(N))){
            dispose();
            AddStudent a = new AddStudent();
            a.setVisible(true);
        }
        else{
        //String N = login.Designation.getSelectedItem().toString();
            try{
                pst = conn.prepareStatement(checking);
                pst.setString(1, Identity);
                pst.setString(2, Pagename);
                rst = pst.executeQuery();
                if(rst.next()){
                    String resid = rst.getString("UserId").trim();
                    String resPage = rst.getString("AccessPage").trim();
                    if((resid.equals(Identity)) && (resPage.equals(Pagename))){
                        dispose();
                        AddStudent a = new AddStudent();
                        a.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
                    }
                    rst.close();
                    pst.close();
                }
                else{
                    JOptionPane.showMessageDialog(null, na+", You have no rights to this Page ok?");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try{
                    rst.close();
                    pst.close();
                }
                catch(Exception e){} 
            }
        }
    }//GEN-LAST:event_StudentActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        // TODO add your handling code here:
        
        String checking = "select * from Access where UserId=? and AccessPage=?";
        String Pagename ="Library";
        //String N = login.Designation.getSelectedItem().toString();
        if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N)) || ("Accountant".equals(N))){
            dispose();
            Library a = new Library();
            a.setVisible(true);
        }
        else{
        //String N = login.Designation.getSelectedItem().toString();
            try{
                pst = conn.prepareStatement(checking);
                pst.setString(1, Identity);
                pst.setString(2, Pagename);
                rst = pst.executeQuery();
                if(rst.next()){
                    String resid = rst.getString("UserId").trim();
                    String resPage = rst.getString("AccessPage").trim();
                    if((resid.equals(Identity)) && (resPage.equals(Pagename))){
                        dispose();
                        AddStudent a = new AddStudent();
                        a.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
                    }
                    rst.close();
                    pst.close();
                }
                else{
                    JOptionPane.showMessageDialog(null, na+", You have no rights to this Page ok?");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try{
                    rst.close();
                    pst.close();
                }
                catch(Exception e){} 
            }
        }
    }//GEN-LAST:event_LibraryActionPerformed

    private void AccountsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountsActionPerformed
        // TODO add your handling code here:
        String checking = "select * from Access where UserId=? and AccessPage=?";
        String Pagename ="Accounts";
        //String N = login.Designation.getSelectedItem().toString();
       if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N)) || ("Accountant".equals(N))){
            dispose();
            Accounts a = new Accounts();
            a.setVisible(true);
        }
        else{
        //String N = login.Designation.getSelectedItem().toString();
            try{
                pst = conn.prepareStatement(checking);
                pst.setString(1, Identity);
                pst.setString(2, Pagename);
                rst = pst.executeQuery();
                if(rst.next()){
                    String resid = rst.getString("UserId").trim();
                    String resPage = rst.getString("AccessPage").trim();
                    if((resid.equals(Identity)) && (resPage.equals(Pagename))){
                        dispose();
                        AddStudent a = new AddStudent();
                        a.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
                    }
                    rst.close();
                    pst.close();
                }
                else{
                    JOptionPane.showMessageDialog(null, na+", You have no rights to this Page ok?");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            finally{
                try{
                    rst.close();
                    pst.close();
                }
                catch(Exception e){} 
            }
        }
    }//GEN-LAST:event_AccountsActionPerformed

    private void adduserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adduserActionPerformed
        // TODO add your handling code here:
        String N = login.Designation.getSelectedItem().toString();
        if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N))){
            dispose();
            Admin a = new Admin();
            a.setVisible(true);
        }
        else{
            String na = login.userName.getText();
            JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
        }
    }//GEN-LAST:event_adduserActionPerformed

    private void grantAcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grantAcessActionPerformed
        // TODO add your handling code here:
        String N =login.Designation.getSelectedItem().toString();
        if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N))){
            Access acc = new Access();
            acc.setVisible(true);
        }
        else{
            String na = login.userName.getText();
            JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
        }
    }//GEN-LAST:event_grantAcessActionPerformed

    private void removeAcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeAcessActionPerformed
        // TODO add your handling code here:
        
        String N =login.Designation.getSelectedItem().toString();
        if (("Admin".equals(N)) || ("Head Teacher".equals(N)) || ("Principle".equals(N))){
            Access acc = new Access();
            acc.setVisible(true);
        }
        else{
            String na = login.userName.getText();
            JOptionPane.showMessageDialog(null, na+", You do not have rights to Access this Page!");
        }
    }//GEN-LAST:event_removeAcessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Accounts;
    private javax.swing.JTextField Answer;
    private javax.swing.JButton DELETE;
    private javax.swing.JLabel Date1;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JButton Library;
    public javax.swing.JLabel NAME;
    private javax.swing.JButton SAVE;
    private javax.swing.JButton SEARCH;
    public static javax.swing.JTextField SEARCH2;
    private javax.swing.JLabel Session;
    private javax.swing.JButton Student;
    private javax.swing.JLabel Time1;
    private javax.swing.JButton UPDATE1;
    private javax.swing.JButton VIEW;
    private javax.swing.JTextField address1;
    private javax.swing.JButton adduser;
    private javax.swing.JTextField contact;
    private javax.swing.JComboBox<String> design;
    private javax.swing.JTextField email;
    private javax.swing.JLabel exans;
    private javax.swing.JLabel exid;
    private javax.swing.JLabel exname;
    private javax.swing.JButton grantAcess;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lablename;
    private javax.swing.JTextField name1;
    private javax.swing.JPasswordField passwrd1;
    private javax.swing.JPasswordField passwrd2;
    private javax.swing.JButton removeAcess;
    private javax.swing.JLabel search1;
    // End of variables declaration//GEN-END:variables

}
